var x = 10;
var y = -x;
console.log("Value of x is: " + x);
console.log("Value of y is: " + y);
var num1 = 10;
var num2 = 2;
var res = 0;
res = num1 + num2;
console.log("Sum:        " + res);
res = num1 - num2;
console.log("Difference: " + res);
res = num1 * num2;
console.log("Product:    " + res);
res = num1 / num2;
console.log("Quotient:   " + res);
res = num1 % num2;
console.log("Remainder:  " + res);
num1++;
console.log("Value of num1 after increment: " + num1);
++num2;
console.log("Value of num2 after pre-increment: " + num2);
--num1;
console.log("Value of num1 after pre-decrement: " + num1);
num2--;
console.log("Value of num2 after decrement: " + num2);
